### ISSUE TITLE
Adopt PSR-2 styling rules

### ISSUE THREAD

**Issue by amyboyd** [zsturgess/overwatch#104]
I'm happy to do this if you want.

**Comment by zsturgess** [comment]
I didn't do this because I personally don't like some of the PSR-2 controls.

But it's better to be consistent than make me happy. I've turned on some more of the code style checks in Scrutinizer and given you access (Settings->Configuration->Buttons along the top), perhaps you can take a look and make sure I haven't missed any? https://scrutinizer-ci.com/g/zsturgess/overwatch

**Comment by zsturgess** [comment]
PHP-CS-Fixer has been added as a custom composer script.
I've run it across the project now, so I'm closing this issue, but if you find anything else squiffy codestyle wise, please open a ticket, or better, send a PR to add it to the list of things PHP-CS-Fixer is looking for!
